ARG version=14.04

FROM ossystems/yocto-env:$version

# Install python3.6 and repo tool
RUN apt-get update && apt-get install -y \
     curl gnupg \
     build-essential checkinstall libreadline-gplv2-dev libncursesw5-dev libssl-dev \
     libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev && \
     rm -rf /var/lib/apt/lists/* && \
     wget https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tar.xz && \
     tar xvf Python-3.6.9.tar.xz && \
     cd Python-3.6.9/ && \
     ./configure && \
     sudo make altinstall -j 16 && \
     curl https://storage.googleapis.com/git-repo-downloads/repo > /bin/repo && chmod a+rx /bin/repo
