ARG version=14.04

FROM ossystems/yocto-env:$version

# Install python3.6 and repo tool
RUN apt-get update
RUN apt-get install -y \
     curl gnupg \
     build-essential checkinstall libreadline-gplv2-dev libncursesw5-dev \
     libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev && \
     rm -rf /var/lib/apt/lists/*

ENV OPENSSL_VERSION="3.0.9"
RUN set -x; apt-get remove libssl-dev -y \
 ### BUILD OpenSSL
 && wget --no-check-certificate -O /tmp/openssl-${OPENSSL_VERSION}.tar.gz "https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz" \
 && tar -xvf /tmp/openssl-${OPENSSL_VERSION}.tar.gz -C /tmp/ \
 && rm -rf /tmp/openssl-${OPENSSL_VERSION}.tar.gz \
 && cd /tmp/openssl-${OPENSSL_VERSION} \
 && ./Configure \
 && make -j 16 \
 && make install \
 && cd .. \
 && rm -rf openssl-${OPENSSL_VERSION}

RUN wget https://www.python.org/ftp/python/3.11.5/Python-3.11.5.tar.xz && \
     tar xvf Python-3.11.5.tar.xz && \
     cd Python-3.11.5/ && \
     ./configure && \
     make altinstall -j 16 && \
     rm -rf ../Python-3.11.5/ && \
     mv /usr/local/lib/python3.11/lib-dynload/_ssl.cpython-311-x86_64-linux-gnu_failed.so /usr/local/lib/python3.11/lib-dynload/_ssl.cpython-311-x86_64-linux-gnu.so && \
     ldconfig

RUN curl https://storage.googleapis.com/git-repo-downloads/repo > /bin/repo && chmod a+rx /bin/repo && \
     sed -i 's|#!/usr/bin/env python|#!/usr/bin/env python3.11|' /bin/repo

